#!/usr/bin/env python3
import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)

"""
tw-ical-export.py — Bulk export Taskwarrior tasks to VEVENT .ics files.

Usage:
  python3 tw-ical-export.py              # export all pending tasks
  python3 tw-ical-export.py --all        # export all tasks including completed
  python3 tw-ical-export.py --clean      # remove .ics files with no matching task
  python3 tw-ical-export.py <filter>     # e.g. project:work or +tag

Only tasks with due: or scheduled: dates generate .ics files.
Run once to initialise ~/.task/time/ics/, then re-run any time to repair.
The hooks (on-add, on-modify) keep things in sync during normal use.
"""

# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime
import json
import subprocess
import argparse

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    cwd = Path.cwd()
    if (cwd / '.git').exists():
        log_dir = cwd / 'logs' / 'debug'
    else:
        log_dir = Path.home() / '.task' / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

sys.path.insert(0, os.path.expanduser('~/.task/scripts'))
from tw_ical_lib import load_config, write_vtodo
from pathlib import Path


def export(filter_args: list, cfg: dict) -> int:
    cmd = ['task', 'rc.hooks=off', 'rc.color=off'] + filter_args + ['export']
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode not in (0, 1):  # task returns 1 for "no matches"
        print(f'tw-ical: task export failed: {result.stderr.strip()}', file=sys.stderr)
        return 1

    tasks = json.loads(result.stdout or '[]')
    written = 0
    for task in tasks:
        write_vtodo(task, cfg)
        if any(task.get(f) for f in ('scheduled', 'due')):
            written += 1

    ics_dir = Path(cfg['ics_dir']).expanduser()
    print(f'tw-ical: {written}/{len(tasks)} tasks have dates → {ics_dir}')
    return 0


def clean(cfg: dict) -> int:
    """Remove .ics files whose uuid no longer exists in taskwarrior."""
    ics_dir = Path(cfg['ics_dir']).expanduser()
    if not ics_dir.exists():
        print('tw-ical: ics_dir does not exist, nothing to clean.')
        return 0

    result = subprocess.run(
        ['task', 'rc.hooks=off', 'rc.color=off', 'export'],
        capture_output=True, text=True,
    )
    known = {t['uuid'] for t in json.loads(result.stdout or '[]')}

    removed = 0
    for ics_file in ics_dir.glob('*.ics'):
        uuid = ics_file.stem
        if uuid not in known:
            ics_file.unlink()
            removed += 1
            print(f'tw-ical: removed orphan {ics_file.name}')

    print(f'tw-ical: cleaned {removed} orphaned .ics files')
    return 0


def main():
    ap = argparse.ArgumentParser(description='Bulk export TW tasks to VTODO .ics')
    ap.add_argument('--all',   action='store_true', help='include completed/deleted tasks')
    ap.add_argument('--clean', action='store_true', help='remove orphaned .ics files')
    ap.add_argument('filter',  nargs='*',           help='taskwarrior filter (default: status:pending)')
    args = ap.parse_args()

    cfg = load_config()

    if args.clean:
        return clean(cfg)

    if args.filter:
        filter_args = args.filter
    elif args.all:
        filter_args = []
    else:
        filter_args = ['status:pending']

    return export(filter_args, cfg)


if __name__ == '__main__':
    sys.exit(main())
