#!/usr/bin/env python3
import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)

"""
tw_ical_lib.py — shared VTODO logic for tw-ical-hook
Imported by on-add_tw-ical.py, on-modify_tw-ical.py, and tw-ical-export.py
"""

# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime, timezone
import json

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    cwd = Path.cwd()
    if (cwd / '.git').exists():
        log_dir = cwd / 'logs' / 'debug'
    else:
        log_dir = Path.home() / '.task' / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

CONFIG_FILE = Path.home() / '.task' / 'config' / 'tw-ical.rc'


# ── Config ─────────────────────────────────────────────────────────────────

def load_config() -> dict:
    cfg = {
        'ics_dir':          '~/.task/time/ics',
        'keep_completed':   'yes',
        'completed_days':   '90',
        'default_duration': 'PT1H',
    }
    if not CONFIG_FILE.exists():
        return cfg
    for line in CONFIG_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' in line:
            k, _, v = line.partition('=')
            cfg[k.strip()] = v.strip()
    return cfg


# ── iCal helpers ───────────────────────────────────────────────────────────

def _escape(text: str) -> str:
    """Escape special characters in iCal text values."""
    return (text.replace('\\', '\\\\')
                .replace(';', '\\;')
                .replace(',', '\\,')
                .replace('\n', '\\n'))


def _fold(line: str) -> str:
    """iCal line folding: max 75 octets per line, continuation indented by space."""
    if len(line.encode('utf-8')) <= 75:
        return line
    parts = []
    while len(line.encode('utf-8')) > 75:
        cut = 75
        while len(line[:cut].encode('utf-8')) > 75:
            cut -= 1
        parts.append(line[:cut])
        line = ' ' + line[cut:]
    parts.append(line)
    return '\r\n'.join(parts)


def _priority(p: str) -> str:
    return {'H': '1', 'M': '5', 'L': '9'}.get(p, '0')


def _vevent_status(s: str) -> str:
    return {
        'completed': 'CANCELLED',   # hide from active calendar view
        'deleted':   'CANCELLED',
    }.get(s, 'CONFIRMED')


# ── Task → VEVENT(s) ────────────────────────────────────────────────────────

# Date fields that each generate their own VEVENT, with summary prefix + X-property
_DATE_FIELDS = [
    ('scheduled', '[sched]', 'SCHEDULED'),
    ('due',       '[due]',   'DUE'),
]


def _vevent_props(task: dict, date_field: str, prefix: str,
                  x_type: str, cfg: dict, now: str) -> list:
    """Return list of (name, value) pairs for one VEVENT."""
    uid      = f"{task['uuid']}-{date_field}@taskwarrior"
    duration = task.get('duration') or cfg.get('default_duration', 'PT1H')
    summary  = f"{prefix} {_escape(task['description'])}"

    props = [
        ('UID',           uid),
        ('DTSTAMP',       now),
        ('CREATED',       task.get('entry',    now)),
        ('LAST-MODIFIED', task.get('modified', now)),
        ('DTSTART',       task[date_field]),
        ('DURATION',      duration.upper()),
        ('SUMMARY',       summary),
        ('STATUS',        _vevent_status(task.get('status', 'pending'))),
        ('X-TW-DATE-TYPE', x_type),
        ('X-TW-UUID',     task['uuid']),
    ]

    if task.get('priority'):
        props.append(('PRIORITY', _priority(task['priority'])))

    cats = list(task.get('tags', []))
    if task.get('project'):
        cats.append('project.' + task['project'].replace(':', '.'))
    if cats:
        props.append(('CATEGORIES', ','.join(_escape(c) for c in cats)))

    if task.get('annotations'):
        desc = '\\n'.join(_escape(a['description']) for a in task['annotations'])
        props.append(('DESCRIPTION', desc))

    if task.get('urgency') is not None:
        props.append(('X-TW-URGENCY', str(round(task['urgency'], 2))))

    return props


def task_to_ical(task: dict, cfg: dict) -> str:
    """Generate a VCALENDAR with one VEVENT per date field present on the task."""
    now = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')

    lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//tw-ical-hook//tw2ical 0.1.1//EN',
    ]

    for field, prefix, x_type in _DATE_FIELDS:
        if not task.get(field):
            continue
        props = _vevent_props(task, field, prefix, x_type, cfg, now)
        lines.append('BEGIN:VEVENT')
        lines += [_fold(f'{k}:{v}') for k, v in props]
        lines.append('END:VEVENT')

    lines += ['END:VCALENDAR', '']
    return '\r\n'.join(lines)


# ── Write / remove ─────────────────────────────────────────────────────────

def write_vtodo(task: dict, cfg: dict):
    """Write (or remove) the .ics file for a task. Name kept for hook compatibility."""
    ics_dir = Path(cfg['ics_dir']).expanduser()
    ics_dir.mkdir(parents=True, exist_ok=True)
    ics_file = ics_dir / f"{task['uuid']}.ics"

    status = task.get('status', 'pending')

    if status == 'deleted':
        ics_file.unlink(missing_ok=True)
        return

    if status == 'completed' and cfg.get('keep_completed', 'yes').lower() == 'no':
        ics_file.unlink(missing_ok=True)
        return

    # Only write if the task has at least one calendar-relevant date
    if not any(task.get(f) for f, _, _ in _DATE_FIELDS):
        ics_file.unlink(missing_ok=True)
        return

    ics_file.write_text(task_to_ical(task, cfg))
